from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime

def generate_pdf_report(
    country: str,
    market_summary: str = "N/A",
    valuation_summary: str = "N/A",
    compliance_summary: str = "N/A",
    user_query: str = ""
) -> BytesIO:
    """
    Generate a PDF report from agent outputs.
    Returns BytesIO buffer ready for Streamlit download.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = styles['Title']
    heading_style = ParagraphStyle('Heading2', parent=styles['Heading2'], spaceAfter=12)
    normal_style = styles['Normal']
    
    elements = []
    
    # Header
    elements.append(Paragraph(f"PropTech Real Estate Report - {country}", title_style))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    elements.append(Paragraph(f"Query: {user_query}", normal_style))
    elements.append(Spacer(1, 24))
    
    # Sections
    sections = [
        ("Market Overview", market_summary),
        ("Valuation Insights", valuation_summary),
        ("Compliance & Regulatory Notes", compliance_summary)
    ]
    
    for title, content in sections:
        elements.append(Paragraph(title, heading_style))
        elements.append(Paragraph(content.replace("\n", "<br/>"), normal_style))
        elements.append(Spacer(1, 12))
    
    # Footer note
    elements.append(Spacer(1, 36))
    elements.append(Paragraph(
        "This report is generated by an AI-powered PropTech advisor. "
        "Always verify with official sources and professional advisors.",
        ParagraphStyle('Footnote', fontSize=8, textColor=colors.gray)
    ))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer